server:
  address: ":6380"

users:
  - username: admin
    password: admin123
    role: admin

  - username: app
    password: app123
    role: writer

  - username: guest
    password: guest
    role: reader

data:
  dir: "data"
  aof_file: "ferrodb.aof"

engine:
  db_count: 16
  cleanup_interval_sec: 1
